return {
  { "catppuccin/nvim" },
  { "EdenEast/nightfox.nvim" },
  { "rebelot/kanagawa.nvim" },
  { "sainnhe/gruvbox-material" },
  { "metalelf0/jellybeans-nvim" },
  -- { "olimorris/onedarkpro.nvim" },
  { "rktjmp/lush.nvim" },
  { "mcchrish/zenbones.nvim" },
  -- { "ellisonleao/gruvbox.nvim" },
  { "folke/tokyonight.nvim" },
  -- { "Mofiqul/dracula.nvim" },
  -- { "glepnir/zephyr-nvim" },
  -- { "loctvl842/monokai-pro.nvim" },
  { "marko-cerovac/material.nvim" },
  -- { "rafamadriz/neon" },
  -- { "ray-x/starry.nvim" },
  -- { "sainnhe/edge" },
  -- { "sainnhe/everforest" },
  -- { "sainnhe/sonokai" },
  -- { "savq/melange-nvim" },
}
